---
- name: Include initial server vars
  ansible.builtin.include_vars: first_server.yml
  when: inventory_hostname in groups['gradient_control_nodes'][0]

- name: Add hostname to rke2_server group
  ansible.builtin.add_host:
    hostname: '{{ inventory_hostname }}'
    groups: rke2_servers

- name: Add hostname to rke2_cluster group
  ansible.builtin.add_host:
    hostname: '{{ inventory_hostname }}'
    groups: rke2_cluster

- name: RKE2 agent and server tasks
  ansible.builtin.include_role:
    name: rke2_common
    tasks_from: main
  vars:
    caller_role_name: server

- name: Setup initial server
  ansible.builtin.include_role:
    name: rke2_server
    tasks_from: first_server
  when: inventory_hostname in groups['gradient_control_nodes'][0]
