---
- name: Check for helm install
  shell: command -v helm > /dev/null 2>&1
  register: helm_check
  ignore_errors: true

- name: Add signing key for installing helm
  ansible.builtin.shell:
    cmd: curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null
  when: helm_check.failed == true

- name: Add apt repository for helm
  ansible.builtin.apt_repository:
    state: present
    repo: deb [signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main
  when: helm_check.failed == true

- name: Install required apt packages
  ansible.builtin.apt:
    pkg:
      - helm
  when: helm_check.failed == true
