---
- name: Include other_servers vars
  ansible.builtin.include_vars: other_servers.yml
  when: inventory_hostname in groups['gradient_control_nodes'][1:]

- name: Add hostname to rke2_server group
  ansible.builtin.add_host:
    hostname: '{{ inventory_hostname }}'
    groups: rke2_servers

- name: Add hostname to rke2_cluster group
  ansible.builtin.add_host:
    hostname: '{{ inventory_hostname }}'
    groups: rke2_cluster

- name: RKE2 agent and server tasks
  ansible.builtin.include_role:
    name: rke2_common
    tasks_from: main
  vars:
    caller_role_name: server

- name: Setup other servers
  ansible.builtin.include_role:
    name: rke2_server
    tasks_from: other_servers
  when: inventory_hostname in groups['gradient_control_nodes'][1:]
