---
- name: Gradient RKE2 Common Tasks
  ansible.builtin.include_role:
    name: gradient_common
    tasks_from: '{{ gradient_common_task }}'
  loop:
    - main
    - install_kubelet_config
    - install_containerd_configuration
  loop_control:
    loop_var: gradient_common_task

- name: Install RKE2 for Initial Server
  ansible.builtin.include_tasks: install_rke2_on_initial_server.yml
  when: inventory_hostname in groups['gradient_control_nodes'][0]

- name: Install RKE2 for Other Servers
  ansible.builtin.include_tasks: install_rke2_on_other_servers.yml
  when: inventory_hostname in groups['gradient_control_nodes'][1:]

- name: Install rke2-coredns HelmConfigChart
  copy:
    dest: /var/lib/rancher/rke2/server/manifests/rke2-coredns-config.yaml
    content: |
      apiVersion: helm.cattle.io/v1
      kind: HelmChartConfig
      metadata:
        name: rke2-coredns
        namespace: kube-system
      spec:
        valuesContent: |-
          autoscaler:
            enabled: false
          replicaCount: {{ rke2_coredns_replica_count }}
          nodeSelector:
            paperspace.com/pool-name: services-small
  when: inventory_hostname in groups['gradient_control_nodes'][0]

- name: Install Terraform
  ansible.builtin.include_tasks: install_terraform.yml

- name: Install Kubectl
  ansible.builtin.include_tasks: install_kubectl.yml

- name: Install Helm
  ansible.builtin.include_tasks: install_helm.yml

- name: Install Stern
  ansible.builtin.include_tasks: install_stern.yml

- name: Install Stern
  ansible.builtin.include_tasks: install_k9s.yml
