---
- name: Gradient RKE2 Common Tasks
  ansible.builtin.include_role:
    name: gradient_common
    tasks_from: '{{ gradient_common_task }}'
  loop:
    - main
    - install_containerd_configuration
  loop_control:
    loop_var: gradient_common_task

- name: Install RKE2 for Initial Server
  ansible.builtin.include_tasks: install_rke2_on_initial_server.yml
  when: inventory_hostname in groups['gradient_control_nodes'][0]

- name: Install RKE2 for Other Servers
  ansible.builtin.include_tasks: install_rke2_on_other_servers.yml
  when: inventory_hostname in groups['gradient_control_nodes'][1:]

- name: Install Terraform
  ansible.builtin.include_tasks: install_terraform.yml

- name: Install Kubectl
  ansible.builtin.include_tasks: install_kubectl.yml

- name: Install Helm
  ansible.builtin.include_tasks: install_helm.yml

- name: Install Stern
  ansible.builtin.include_tasks: install_stern.yml

- name: Install Stern
  ansible.builtin.include_tasks: install_k9s.yml
