---
- name: Setup Gradient Control Nodes
  hosts: gradient_control_nodes
  any_errors_fatal: true
  become: true
  collections:
    - paperspace.ansible_gradient_installer
  tasks:
    - name: 'Import Gradient Control Node Role'
      ansible.builtin.import_role:
        name: paperspace.ansible_gradient_installer.gradient_control_node
  vars:
    containerd_cluster_domain: https://graphcore.paperspacegradient.com
    containerd_local_host_and_port: http://localhost:5000
  serial: 1

- name: Setup Gradient Worker Nodes
  hosts: gradient_worker_nodes
  any_errors_fatal: true
  become: true
  collections:
    - paperspace.ansible_gradient_installer
  tasks:
    - name: 'Import Gradient Worker Node Role'
      ansible.builtin.import_role:
        name: paperspace.ansible_gradient_installer.gradient_worker_node
  vars:
    containerd_cluster_domain: https://graphcore.paperspacegradient.com
    containerd_local_host_and_port: http://localhost:5000
  serial: 2

- name: Setup Gradient Service Nodes
  hosts: gradient_service_nodes
  any_errors_fatal: true
  become: true
  collections:
    - paperspace.ansible_gradient_installer
  tasks:
    - name: 'Import Gradient Service Node Role'
      ansible.builtin.import_role:
        name: paperspace.ansible_gradient_installer.gradient_service_node
  vars:
    containerd_cluster_domain: https://graphcore.paperspacegradient.com
    containerd_local_host_and_port: http://localhost:5000
  serial: 2
