---
- name: Validate pool_name is set
  ansible.builtin.fail:
    msg: "Failed: All worker nodes are required to have a pool_name set within the hosts.ini"
  when: pool_name is undefined

- name: Add hostname to rke2_agents group
  ansible.builtin.add_host:
    hostname: '{{ inventory_hostname }}'
    groups: rke2_agents

- name: Add hostname to rke2_cluster group
  ansible.builtin.add_host:
    hostname: '{{ inventory_hostname }}'
    groups: rke2_cluster

- name: Setup RKE2 Agent
  ansible.builtin.include_role:
    name: rke2_agent
    tasks_from: main
  vars:
    rke2_config:
      kubelet-arg:
        - "config=/etc/rancher/rke2/kubelet-config.yaml"
      node-label:
        - "paperspace.com/pool-name={{ pool_name }}"
        - "node.kubernetes.io/instance-type={{ pool_name }}"
        - "node-role.kubernetes.io/worker=true"

- name: Add limitMemLock=infinity on rke2-agent.service
  ansible.builtin.lineinfile:
    path: /usr/local/lib/systemd/system/rke2-agent.service
    state: present
    regexp: '^LimitMEMLOCK.*'
    line: "LimitMEMLOCK=infinity"

- name: Restart rke2-agent
  ansible.builtin.systemd:
    name: rke2-agent.service
    state: started
    enabled: true
    daemon_reload: true
