---
- name: Create containerd cgroups
  ansible.builtin.file:
    path: '/etc/rancher/rke2'
    state: directory
    mode: 0755

- name: Install Gradient RKE2 KubeletConfig File
  copy:
    dest: /etc/rancher/rke2/kubelet-config.yaml
    content: |
      apiVersion: kubelet.config.k8s.io/v1beta1
      kind: KubeletConfiguration
      kubeReserved:
        cpu: 500m
        memory: 256Mi
        ephemeral-storage: 10Gi
      kubeReservedCgroup: /podruntime.slice
      systemReserved:
        cpu: 500m
        memory: 256Mi
        ephemeral-storage: 5Gi
      systemReservedCgroup: /system.slice
