---
- name: Cluster RKE2 Common Tasks
  ansible.builtin.include_role:
    name: gradient_common
    tasks_from: '{{ gradient_common_task }}'
  loop:
    - main
    - install_containerd_configuration
    - install_kubelet_config
    - install_rke2_agent
  loop_control:
    loop_var: gradient_common_task
