name: release
on:
  push:
    tags:
      - "*"

defaults:
  run:
    working-directory: .

jobs:
  docker:
    name: docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          push: true
          tags: |
            paperspace/gradient-installer:latest
            paperspace/gradient-installer:0.0.0-latest
            paperspace/gradient-installer:${{ github.ref_name}}

  upload_assets:
    name: upload-assests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # TODO install jq?
      - run: bin/build ${{ github.ref_name }}
      - run: bin/upload ${{ github.ref_name }}
        env:
          GH_TOKEN: ${{ secrets.PSBOT_GITHUB_TOKEN }}
